package com.songPlayer;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.Arrays;
import java.util.LinkedList;
import java.util.List;
import java.util.stream.Collectors;

import com.songPlayer.command.CommandInvoker;
import com.songPlayer.config.ApplicationConfig;
import com.songPlayer.exceptions.NoSuchCommandException;
import com.songPlayer.exceptions.NoSuchDataException;
import com.songPlayer.repositories.data.DataLoader;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void run(List<String> commandLineArgs){
        ApplicationConfig appConfig = new ApplicationConfig();
        DataLoader dataLoader = appConfig.getDataLoader();
        CommandInvoker commandInvoker = appConfig.getCommandInvoker();

        BufferedReader reader;
        String inputFile = commandLineArgs.get(0).split("=")[1];
        commandLineArgs.remove(0);
        
        for(String arg: commandLineArgs){
            String[] splits = arg.split("=");
            try{
                dataLoader.executeData(splits[0], splits[1]);
            }
            catch(NoSuchDataException e){
                e.printStackTrace();
            }
        }
        try{
            reader = new BufferedReader(new FileReader(inputFile));
            String line = reader.readLine();
            while(line != null){
                List<String> tokens = Arrays.asList(line.split(" "));
                String commandName = tokens.get(0);
                commandInvoker.executeCommand(commandName ,tokens);
                line = reader.readLine();
            }
            reader.close();
        }
        catch(IOException | NoSuchCommandException e){
            e.printStackTrace();
        }
        
    }
    

    public static void main(String[] args) {
        List<String> commandLineArgs = new LinkedList<>(Arrays.asList(args));
//        List<String> commandLineArgs = new LinkedList<>(Arrays.asList("INPUT-FILE=./temp/input.txt","SONG-DATA=./temp/song.csv"));
        String expectedArgs = "INPUT-FILE$SONG-DATA";
        String actualArgs = commandLineArgs.stream()
                                    .map(a -> a.split("=")[0])
                                    .collect(Collectors.joining("$"));
        if(expectedArgs.equals(actualArgs)){
            run(commandLineArgs);
        }
    }
}
